### ISSUE TITLE
Add table circleci_insights_workflows

### ISSUE THREAD

**Issue by leonid-panich** [turbot/steampipe-plugin-circleci#5]
Hello
It would be great to have information about all workflow runs with filtering by branch, start-date and end-date.

**References**
Documentation: 
https://circleci.com/docs/api/v2/index.html#operation/getProjectWorkflowRuns

Endpoint:
GET https://circleci.com/api/v2/insights/{project-slug}/workflows/{workflow-name}

Go SDK used in this project has no methods for this table

**Comment by misraved** [comment]
Welcome to Steampipe @leonid-panich and thanks for raising the issue for the new table 👍.

The first step for this table would be to update the Go SDK with the relevant `GET Endpoint` and then add support for this table. Apologies, but there are no immediate plans to implement this table due to other priorities, however, we always appreciate any PRs and are willing to help along the way!

If anyone would like to attempt to develop this table, the API mentioned by @leonid-panich is an excellent place to start.

Please let us know in case there are questions 👍.

**Comment by leonid-panich** [comment]
Hello @misraved, 
I've created a PR to add this table.
Can you, please, check it?

**Comment by leonid-panich** [comment]
Hello @misraved @luisffc @dboeke, 
it would be great if someone could check the PR
